
## 1½ - Data
\

This page introduces the data sets you'll be using during the course. You will be using one data set during the at-home worksheets, and another biological data set to complete the tasks set during online workshops.  

$~$

### **GAMES DATA**
\ 

_The **GAMES** data will be used for Chapters to be completed at home._

This data is based on some simple
games/tests and basic information about yourselves. Each variable has
a specific distribution.
The data is stored anonymously.  

The questions are outlined below, and at the bottom of this page is a form which you should use to submit your data.  
\

Click continue to see variables...


$~$

#### **VARIABLES IN THE GAMES DATA**
\

1. **ROLE**, saved as `role` in the data, is one of:

* _student_ at Lincoln (coded as `student` in the data)
* _staff_ at Lincoln (coded as `staff` in the data)
* _external_ to Lincoln (coded as `external` in the data)
* _child_ (coded as `child` in the data)
* _baby_ (coded as `baby` in the data)

2. **TUTOR GROUP**: your tutor group ID for the module. 
See document on blackboard if you're not sure.
This information will be coded anonymously so that it is not clear which tutor
group is which (makes everything even more anonymous).
Saved as `group` in the data.

3. **EYESIGHT**: your **glasses prescription** (if any). 
If you have a different prescription for 
each eye then take the average.
Saved as `eyesight` in the data.

4. **CONTINENTS**: how many continents you've visited in your life (
including your home continent).
Saved as `continents` in the data.

5. **COUNTRIES**: how many countries you've visited in your life 
(including your home country).
Saved as `countries` in the data-

6. **HEARING**: your score in the hearing test (see below).
Saved as `hearing` in the data.

7. **REACTION** your score in the reaction test (see below). 
Saved as `reaction` in the data.

8. **HARDWARE**, saved as `hardware` in the data, is whether for the two games above, you were using a:

* mouse (coded as `mouse` in the data)
* touchpad or touchscreen (coded as `touch` in the data)  

$~$

##### **HIGH FREQUENCY HEARING TEST**

For the following test you'll need speakers or earphones. Please make sure that the volume is not turned up too loud!  

Once you click, a noise will be produced, starting from 20000Hz and decreasing. You need to click again as soon as you hear the noise. Younger people tend to be able to hear higher frequencies.  

If, for whatever reason, you are unable to take the test, please skip this question.  
\

<div align="center">
   <iframe width="360" height="540" src="https://humanbenchmark.com/tests/hearing" frameborder="0" allowfullscreen>
   </iframe>
</div>

$~$

##### **REACTION TEST**

This reaction test will measure your reaction time three times; please record the average time in the form. Note: although the test involves clicking when a colour turns from red to green, the test is still suitable for those with any kind of colour blindness as the prompt will change from "Wait for green" to "Click!"  
\

<div align="center">
   <iframe width="360" height="540" src="https://humanbenchmark.com/tests/reactiontime/" frameborder="0" allowfullscreen>
   </iframe>
</div>

$~$

##### **FORM FOR COMPLETING GAMES DATA**

<div align="center">
  <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSevukh74bKwyNouV3g3An5bg0pKV2WeIvI_bLT6nlnSnOD03w/viewform?embedded=true" width="640" height="1138" frameborder="0" marginheight="0" marginwidth="0">Loading…
  </iframe>
</div>
\


### **BIOLOGICAL DATA**
\

_The **BIOLOGICAL** data consists of data sets that you'll work on in online workshops_.  

There are three data sets: 

* TO BE COMPLETED
